---
abstract: 'Perl implementation of DMARC'
author:
  - 'Matt Simerson <msimerson@cpan.org>'
  - 'Davide Migliavacca <shari@cpan.org>'
  - 'Marc Bradshaw <marc@marcbradshaw.net>'
build_requires:
  Module::Build: '0.3601'
  Test::Exception: '0'
  Test::File::ShareDir: '0'
  Test::More: '0'
  Test::Output: '0'
configure_requires:
  File::ShareDir::Install: '0.06'
  Module::Build: '0.3601'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-DMARC
provides:
  Mail::DMARC:
    file: lib/Mail/DMARC.pm
    version: '1.20210220'
  Mail::DMARC::Base:
    file: lib/Mail/DMARC/Base.pm
    version: '1.20210220'
  Mail::DMARC::HTTP:
    file: lib/Mail/DMARC/HTTP.pm
    version: '1.20210220'
  Mail::DMARC::Policy:
    file: lib/Mail/DMARC/Policy.pm
    version: '1.20210220'
  Mail::DMARC::PurePerl:
    file: lib/Mail/DMARC/PurePerl.pm
    version: '1.20210220'
  Mail::DMARC::Report:
    file: lib/Mail/DMARC/Report.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate:
    file: lib/Mail/DMARC/Report/Aggregate.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Metadata:
    file: lib/Mail/DMARC/Report/Aggregate/Metadata.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record:
    file: lib/Mail/DMARC/Report/Aggregate/Record.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Auth_Results:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Auth_Results.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Auth_Results::DKIM:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Auth_Results/DKIM.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Auth_Results::SPF:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Auth_Results/SPF.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Identifiers:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Identifiers.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Row:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Row.pm
    version: '1.20210220'
  Mail::DMARC::Report::Aggregate::Record::Row::Policy_Evaluated:
    file: lib/Mail/DMARC/Report/Aggregate/Record/Row/Policy_Evaluated.pm
    version: '1.20210220'
  Mail::DMARC::Report::Receive:
    file: lib/Mail/DMARC/Report/Receive.pm
    version: '1.20210220'
  Mail::DMARC::Report::Send:
    file: lib/Mail/DMARC/Report/Send.pm
    version: '1.20210220'
  Mail::DMARC::Report::Send::HTTP:
    file: lib/Mail/DMARC/Report/Send/HTTP.pm
    version: '1.20210220'
  Mail::DMARC::Report::Send::SMTP:
    file: lib/Mail/DMARC/Report/Send/SMTP.pm
    version: '1.20210220'
  Mail::DMARC::Report::Sender:
    file: lib/Mail/DMARC/Report/Sender.pm
  Mail::DMARC::Report::Store:
    file: lib/Mail/DMARC/Report/Store.pm
    version: '1.20210220'
  Mail::DMARC::Report::Store::SQL:
    file: lib/Mail/DMARC/Report/Store/SQL.pm
    version: '1.20210220'
  Mail::DMARC::Report::Store::SQL::Grammars::MySQL:
    file: lib/Mail/DMARC/Report/Store/SQL/Grammars/MySQL.pm
    version: '1.20210220'
  Mail::DMARC::Report::Store::SQL::Grammars::PostgreSQL:
    file: lib/Mail/DMARC/Report/Store/SQL/Grammars/PostgreSQL.pm
    version: '1.20210220'
  Mail::DMARC::Report::Store::SQL::Grammars::SQLite:
    file: lib/Mail/DMARC/Report/Store/SQL/Grammars/SQLite.pm
    version: '1.20210220'
  Mail::DMARC::Report::URI:
    file: lib/Mail/DMARC/Report/URI.pm
    version: '1.20210220'
  Mail::DMARC::Result:
    file: lib/Mail/DMARC/Result.pm
    version: '1.20210220'
  Mail::DMARC::Result::Reason:
    file: lib/Mail/DMARC/Result/Reason.pm
    version: '1.20210220'
  Mail::DMARC::Test::Transport:
    file: lib/Mail/DMARC/Test/Transport.pm
recommends:
  Mail::DKIM: '0'
  Net::IMAP::Simple: '0'
  Net::SMTPS: '0'
requires:
  Carp: '0'
  Config::Tiny: '0'
  DBD::SQLite: '1.31'
  DBIx::Simple: '1.35'
  Data::Dumper: '0'
  Email::MIME: '0'
  Email::Simple: '0'
  Encode: '0'
  English: '0'
  File::ShareDir: '1.00'
  Getopt::Long: '0'
  HTTP::Tiny: '0'
  IO::Compress::Gzip: '0'
  IO::Compress::Zip: '0'
  IO::File: '0'
  IO::Socket::SSL: '0'
  IO::Uncompress::Gunzip: '0'
  IO::Uncompress::Unzip: '0'
  Net::DNS::Resolver: '0'
  Net::IDN::Encode: '0'
  Net::IP: '0'
  Net::SSLeay: '0'
  POSIX: '0'
  Pod::Usage: '0'
  Regexp::Common: '2013031301'
  Socket: '0'
  Socket6: '0.23'
  Sys::Hostname: '0'
  Sys::Syslog: '0'
  Test::File::ShareDir: '0'
  URI: '0'
  XML::LibXML: '0'
resources:
  bugtracker: https://github.com/msimerson/mail-dmarc/issues
  homepage: https://github.com/msimerson/mail-dmarc/wiki
  license: http://dev.perl.org/licenses/
  repository: https://github.com/msimerson/mail-dmarc
version: '1.20210220'
x_contributors:
  - 'Benny Pedersen <me@junc.eu>'
  - 'Jean Paul Galea <jeanpaul@yubico.com>'
  - 'Marisa Clardy <marisa@clardy.eu>'
  - 'Priyadi Iman Nurcahyo <priyadi@priyadi.net>'
  - 'Ricardo Signes <rjbs@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
