name: CI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

permissions:
  contents: read

jobs:
  perl_tester:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.40"
          - "5.26"

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Install Perl Modules with cpanm
        uses: perl-actions/install-with-cpanm@v2
        continue-on-error: true
        with:
          install: |
            Regexp::Common
            Config::Tiny
            File::ShareDir
            Net::DNS::Resolver
            DBD::SQLite
            DBD::Pg
            DBD::mysql
            Net::IP
            Socket6
            Email::MIME
            Net::SMTPS
            XML::LibXML
            Email::Sender
            DBIx::Simple
            HTTP::Tiny
            Test::File::ShareDir
            Test::Output
            Test::Exception
            CGI
            XML::Validator::Schema
            Net::DNS::Resolver::Mock
          sudo: false

      - run: perl Makefile.PL
      - run: make test
